version: '3.3'

services:

  bandersnatch:
    # home made build
    image: pyie/bandersnatch:pi
    restart: always

    volumes:
      # how to store
      - ./bandersnatch.conf:/etc/bandersnatch.conf
      # where to store (ext. USB HDD mount point)
      - /media/pi/PypiMirror/mirror:/pypi
      # what to store
      - /home/pi/mirror/requirements:/requirements

    command: python /bandersnatch/src/runner.py --config=/etc/bandersnatch.conf 3600


  nginx:
    image: nginx:1.19
    restart: always
    depends_on:
      - bandersnatch
    volumes:
      - type: bind
        source: /media/pi/PypiMirror/mirror
        target: /pypi
        read_only: true

      - ./nginx:/etc/nginx
    ports:
      - "80:80"
