version: '3.8'

services:

  pypiserver:
    image: pypiserver/pypiserver:v1.4.2
    restart: always
    command: --disable-fallback /data/packages


    volumes:
      - type: bind
        source: ./pypiserver
        target: /data/packages
# this would be /media/<user>/Toshiba/....
#    volumes:
#      - ./pypiserver:/data/packages
    ports:
      - "9090:8080"

  nginx:
    image: nginx:1.19
    restart: always
    volumes:
      - ./pypiserver:/data/packages
      - ./cache:/cache
      - ./nginx:/etc/nginx
    ports:
      - "80:80"
    depends_on:
      - pypiserver
    links:
      - pypiserver
